version: "3"
services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: petstore
  petstore:
    build:
      context: .
      dockerfile: ./build/Dockerfile
    image: petstore:latest
    container_name: petstore
    depends_on:
      - postgres
    environment:
      APP_API_PORT: 8080
      APP_API_BASEURL: "/api"
      APP_POSTGRESQL_URL: postgres://postgres:admin@postgres:5432
      APP_POSTGRESQL_DATABASE: petstore
    ports:
      - "8080:8080"
    restart: always